- main.tf
If the source file is passed to this module, it will never be updated. Implemented the `source_code_hash` so that the Lambda itself will be updated in the scenario's where the Lambda code is directly passed to the module
One of the few locations this happens is in the [`CloudFront` module](https://github.com/schubergphilis/terraform-aws-mcaf-cloudfront/blob/master/auth.tf#L66).
> Update Lambda if the given source file changes

- main.tf
- variables.tf
Add support for [Lambda Layers](https://docs.aws.amazon.com/lambda/latest/dg/configuration-layers.html) ([Terraform](https://www.terraform.io/docs/providers/aws/r/lambda_function.html#lambda-layers))
> [IOT-543] Add support for Lambda Layers

- outputs.tf
output "name" needed for mapping Lambda function name in aws_lambda_permission, for  cloudwatch event
> added output "name" for Lambda

- main.tf
```Error: Error in function call
on .terraform/modules/usecase_o05a.material_quality_api/main.tf line 96, in resource "aws_s3_bucket_object" "s3_dummy":
96:   count  = contains(concat(data.aws_s3_bucket_objects.s3_objects.*.keys, list()), var.s3_key) ? 0 : 1
Call to function "list" failed: at least one argument is required.```
> Fix empty list

- main.tf
Fix the local filename: `local_filename` is `data.archive_file.dummy.output_path` if no filename is specified, so this breaks creating Lambda's with S3 (since S3 and filename are then always specified)
```
Error: "s3_bucket": conflicts with filename
on .terraform/modules/usecase_o05a.material_quality_api/main.tf line 108, in resource "aws_lambda_function" "default":
108: resource "aws_lambda_function" "default" {```
> Fix filename/S3 configuration issue

- main.tf
- variables.tf
When using this module in combination with `data.archive_file` it fails because `filebase64sha256()` is called before the data resource is refreshed.
By using the `output_base64sha256` output from `data.archive_file` we get around this, but need a way to pass in this value, thus introduce the `source_code_hash` variable to optionally set the value and if not for the module to compute it.
Signed-off-by: Stephen Hoekstra <shoekstra@schubergphilis.com>
> Add `source_code_hash` variable

- main.tf
- Add `kms_key_id` to `aws_cloudwatch_log_group`
- Ignore tfsec warning for open egress rule (see [here](https://tfsec.dev/docs/aws/vpc/no-public-egress-sg/) for more info)
> Encrypt CloudWatch log group

- .github/workflows/terraform.yml
- main.tf
- variables.tf
- versions.tf
This PR tweaks the code to make it compatible with the "new" V4 version of the AWS provider.
Change:
- Version explicitly set to` > 4.0.0`
- Changes `aws_s3_bucket_object ` to `aws_s3_object` (will recreate the object)
Tweaks:
- Changed the "default" runtime to the latest Python version: `python3.9`
- Added `tags` to the `aws_s3_object` dummy. Mainly done for insights (so it's clear where it comes from), so also added the Lambda name as a tag
- Updated `tf-sec` security check (old one broke) and suppressed the tracing warning. Low impact and it can be set with a variable
> Update module to Provider V4

- main.tf
- variables.tf
Currently the lambda function gets a default egress rule that allows all traffic. This causes findings in security hub and is difficult to explain in PCIDSS firewall reviews. This PR adds a variable to control the creation of the egress rule. By default this is off to set a secure default, but when this is enabled, the original behaviour is replicated.
> Add egress sg rule var

- main.tf
Add an empty ingress and egress definition to remove existing security group rules that were previously created by inline rules. Now these are moved to external security group rule definitions to allow the egress to be enabled and disabled via a count.
> add empty egress and ingress inline definition

- main.tf
- variables.tf
When using this module in combination with S3 bucket as deployment package source, a dummy artifact is created and uploaded to the S3 bucket. But this means it is not possible to reference an existing deployment package from S3 as this module overwrites it with the dummy artifact.
So added a variable create_s3_dummy_object which controls the creation of dummy artifact with default value set to true so the original behavior remains the same.
> added variable create_s3_dummy_object_var

- main.tf
When unsetting the `subnet_ids` from a running Lambda it tries to delete the SG before updating the Lambda. As a result the SG cannot be deleted and TF runs fail.
This PR adds lifecycle configuration to change this behaviour with deletion, based on:
- https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/security_group#change-of-name-or-name-prefix-value
- https://github.com/hashicorp/terraform-provider-aws/issues/10329#issuecomment-830697533
- https://github.com/hashicorp/terraform/issues/17614
> Update dependency flow of the default SG

- main.tf
- variables.tf
This PR adds the configuration of the Architecture of the Lambda.
Default is `x86_64`, setting it explicitly (what happens with this code) does not recreate/alter the Lambda, so this should be safe.
See also: https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/lambda_function#architectures
> Add support to specify the architecture

- main.tf
This PR adds the (missing) tags to the Cloudwatch Log Group. Handy for cost insight.
Documentation: https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/cloudwatch_log_group#tags
> Add (missing) tags to the Cloudwatch log group

- .github/workflows/terraform.yml
- README.md
- main.tf
- variables.tf
- The variable `kms_key_arn` will encrypt both the cloudwatch log group and the environmental variables of the lambda, but if this configuration is provided when environment variables are not in use, the AWS Lambda API does not save this configuration and Terraform will show a perpetual difference of adding the key. To fix the perpetual difference, the kms key will only be passed down to the lambda if environmental variables are specified. https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/lambda_function
- Fix issue with github actions
> Be able to set a KMS key even if there are no environmental variables specified

- main.tf
- versions.tf
- Remove explicit configuration alias
- This removes the need to provide a `providers = { aws.lambda = aws }` argument for this module and any modules that depend on this module
- After this change, the provider will simply default to `aws` and if a different provider is needed, one can be provisioned like this.
```hcl
provider "aws" {
region = "us-west-2"
}
provider "aws" {
alias  = lambda
region = "us-west-2"
}
module "lambda_securityhub_events_suppressor" {
source                       = "github.com/schubergphilis/terraform-aws-mcaf-lambda?ref=v0.3.3"
providers                    = { aws.lambda = aws.lambda }
providers                    = { aws.lambda = aws }
providers                    = { aws = aws.lambda }
}
```
- For example, the `providers` argument can be removed from …
> breaking: remove explicit configuration alias

- .pre-commit-config.yaml
- main.tf
By default the sourcecode_hash is used for local file deployments. 
But in some cases we want to update the lambda from terraform when using S3 files. This is supported by the sourcecode_hash
https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/lambda_function#source_code_hash
When using this with s3_bucket and s3_key the module behaves as following:
source_code_hash = null -> no deployment when s3 file changes (previous behaviour)
source_code_hash = s3object.etag -> terraform will update function
Updated the Pre-commit to current versions and allow for no aws keys
> fix: Allow sourcecode hash also for s3

- README.md
- main.tf
- moved.tf
- outputs.tf
- variables.tf
This PR refactors all the logic and complexity of creating roles and policies by replacing it with the mcaf-role module.
Unfortunately the `create_policy` boolean is still needed since TF doesn't like the `var.string !== null` checks
> feature: Refactor role and policy

- main.tf
- outputs.tf
This PR fixes the "Is a roleArn given?" check.
The length workaround introduced in https://github.com/schubergphilis/terraform-aws-mcaf-lambda/releases/tag/v1.4.0 is not sufficient, even is `null` is given the `length([null])` check will return 1. The fix is using the `compact` function, which removes null values from a list ([source](https://developer.hashicorp.com/terraform/language/functions/compact))
> fix: Fix the check on given RoleArn

- README.md
- main.tf
- variables.tf
**:hammer_and_wrench: Summary**
Restored the variable create_policy.
**:rocket: Motivation**
When calling the lambda from a module in a module. Terraform can't always calculate the count requirement and the module fails. Returning this variable forces the module to work with the policy
**:pencil: Additional Information**
create_poliy was removed in 2.0.0, but is breaking some builds.
No breacking change
> fix: create_policy is required in some situations
